{
  "props": {
    "singleton": false,
    "version": "0.1",
    "author": "uxredbyte",
    "description": "трей",
    "disabled": false
  },
  "components": {
    "systemTray": {
      "type": "script\\SystemTrayScript",
      "x": 176,
      "y": 176,
      "props": {
        "visible": "1",
        "tooltip": "Нажмите правой кнопкой по иконки :)",
        "icon": ".data/img/logo.png",
        "alwaysShowing": true
      }
    }
  }
}